ARG X__HIVE_METASTORE__IMAGE_TAG

# Builds Hive Metastore with all necessary dependencies.
FROM apache/hive:${X__HIVE_METASTORE__IMAGE_TAG}

ENV SERVICE_NAME metastore
ENV DB_DRIVER postgres

# Install and configure Java packages necessary to work
# with PostgreSQL and S3-compatible storages.
USER root
ADD https://jdbc.postgresql.org/download/postgresql-42.7.5.jar /opt/hive/lib/postgresql-42.7.5.jar
RUN cp /opt/hive/lib/postgresql-42.7.5.jar /opt/hadoop/share/hadoop/common/lib/postgresql-42.7.5.jar \
    && cp /opt/hadoop/share/hadoop/tools/lib/hadoop-aws-3.3.6.jar /opt/hadoop/share/hadoop/common/lib/hadoop-aws-3.3.6.jar \
    && cp /opt/hadoop/share/hadoop/tools/lib/aws-java-sdk-bundle-1.12.367.jar /opt/hadoop/share/hadoop/common/lib/aws-java-sdk-bundle-1.12.367.jar \
    && cp /opt/hadoop/share/hadoop/tools/lib/wildfly-openssl-1.1.3.Final.jar /opt/hadoop/share/hadoop/common/lib/wildfly-openssl-1.1.3.Final.jar \
    && cp /opt/hadoop/share/hadoop/common/lib/hadoop-aws-3.3.6.jar /opt/hive/lib/hadoop-aws-3.3.6.jar \
    && cp /opt/hadoop/share/hadoop/common/lib/aws-java-sdk-bundle-1.12.367.jar /opt/hive/lib/aws-java-sdk-bundle-1.12.367.jar \
    && cp /opt/hadoop/share/hadoop/common/lib/wildfly-openssl-1.1.3.Final.jar /opt/hive/lib/wildfly-openssl-1.1.3.Final.jar

# Install envsubst (part of gettext utility) that will
# be used to substitute parameters in configuration
# with the ones provided via the environment variables.
RUN apt-get update && apt-get install -y gettext-base

COPY core-site.xml.template /opt/hive/conf/core-site.xml.template
COPY hive-site.xml.template /opt/hive/conf/hive-site.xml.template

COPY entrypoint.sh /entrypoint-wrapper.sh
RUN chmod +x /entrypoint-wrapper.sh
ENTRYPOINT ["/entrypoint-wrapper.sh"]
