# Configure the "bank" catalog (which contains info about
# tables that are provided in the task) to use Iceberg format
# and search metadata in the Hive metastore.
#
# Note: database configuration is not required here, as
# it is managed by the external metastore.
spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
spark.sql.catalog.bank=org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.bank.type=hive
spark.sql.catalog.bank.uri=thrift://hive-metastore:9083
spark.sql.catalog.bank.warehouse=s3a://bank/warehouse

# Use Minio (S3-compatible storage) filesystem
# to perform Spark operations.
spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem
spark.hadoop.fs.s3a.endpoint=http://minio:9000
spark.hadoop.fs.s3a.access.key=minio-user
spark.hadoop.fs.s3a.secret.key=minio-password
spark.hadoop.fs.s3a.path.style.access=true
spark.hadoop.fs.s3a.connection.ssl.enabled=false
spark.hadoop.fs.s3a.aws.credentials.provider=org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider

# spark.sql.catalogImplementation=hive
# spark.hadoop.hive.metastore.uris=thrift://hive-metastore:9083
