# Common attributes for Airflow services.
x-airflow-common: &airflow-common
  build:
    context: "airflow"
    dockerfile: "Dockerfile.${MOD?error}"
    args:
      X__AIRFLOW__IMAGE_TAG: "${HA5__AIRFLOW__IMAGE_TAG?error}"
  volumes:
    - "./airflow/dags:/opt/airflow/dags"
    - "./logs/airflow:/opt/airflow/logs"
    - "./airflow/plugins:/opt/airflow/plugins"
  environment: &airflow-common-environment
    HA5__AIRFLOW__PORT: "${HA5__AIRFLOW__PORT?error}"
    HA5__AIRFLOW__HOST_NAME: "${HA5__AIRFLOW__HOST_NAME?error}"
    HA5__AIRFLOW__POSTGRES__PORT: "${HA5__AIRFLOW__POSTGRES__PORT?error}"
    HA5__AIRFLOW__POSTGRES__HOST_NAME: "${HA5__AIRFLOW__POSTGRES__HOST_NAME?error}"
    HA5__AIRFLOW__POSTGRES__DB: "${HA5__AIRFLOW__POSTGRES__DB?error}"
    HA5__AIRFLOW__POSTGRES__USER: "${HA5__AIRFLOW__POSTGRES__USER?error}"
    HA5__AIRFLOW__POSTGRES__PASSWORD: "${HA5__AIRFLOW__POSTGRES__PASSWORD?error}"
    HA5__AIRFLOW__USER: "${HA5__AIRFLOW__USER}"
    HA5__AIRFLOW__PASSWORD: "${HA5__AIRFLOW__PASSWORD}"
  depends_on: &airflow-common-depends-on
    airflow-postgres:
      condition: "service_healthy"
  networks:
    - "private"

services:
  # ------------ MINIO ------------

  # The S3-compatible storage designed to store
  # CSVs and Iceberg tables.
  minio:
    image: "quay.io/minio/minio:${HA5__MINIO__IMAGE_TAG?error}"
    command:
      [
        "minio",
        "server",
        "/data",
        "--address",
        ":${HA5__MINIO__API__PORT?error}",
        "--console-address",
        ":${HA5__MINIO__UI__PORT?error}",
      ]
    environment:
      - "MINIO_ROOT_USER=${HA5__MINIO__USER?error}"
      - "MINIO_ROOT_PASSWORD=${HA5__MINIO__PASSWORD?error}"
    volumes:
      - "minio-data:/data"
    ports:
      - "127.0.0.1:${HA5__MINIO__API__LOCAL_PORT?error}:${HA5__MINIO__API__PORT?error}"
      - "127.0.0.1:${HA5__MINIO__UI__LOCAL_PORT?error}:${HA5__MINIO__UI__PORT?error}"
    hostname: "${HA5__MINIO__HOST_NAME?error}"
    networks:
      - "private"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -fsS http://localhost:${HA5__MINIO__API__PORT?error}/minio/health/live >/dev/null",
        ]
      interval: 10s
      timeout: 5s
      retries: 10

  # ----------- AIRFLOW -----------

  # PostgreSQL database designed for
  # storing Airflow data.
  airflow-postgres:
    image: "postgres:${HA5__AIRFLOW__POSTGRES__IMAGE_TAG?error}"
    environment:
      - "POSTGRES_DB=${HA5__AIRFLOW__POSTGRES__DB?error}"
      - "POSTGRES_USER=${HA5__AIRFLOW__POSTGRES__USER?error}"
      - "POSTGRES_PASSWORD=${HA5__AIRFLOW__POSTGRES__PASSWORD?error}"
    volumes:
      - "airflow-postgres-data:/var/lib/postgresql/data"
    networks:
      - "private"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${HA5__AIRFLOW__POSTGRES__DB?error}"]
      interval: "10s"
      retries: 5
      start_period: "5s"

  # Checks Airflow setup, verify that the correct
  # permissions are set on the files.
  airflow-init:
    <<: *airflow-common
    entrypoint: "/bin/bash"
    command:
      - -c
      - |
        envsubst < /opt/airflow/config/airflow.cfg.template > /opt/airflow/config/airflow.cfg
        one_meg=1048576
        mem_available=$$(($$(getconf _PHYS_PAGES) * $$(getconf PAGE_SIZE) / one_meg))
        cpus_available=$$(grep -cE 'cpu[0-9]+' /proc/stat)
        disk_available=$$(df / | tail -1 | awk '{print $$4}')
        warning_resources="false"
        if (( mem_available < 4000 )) ; then
          echo
          echo -e "\033[1;33mWARNING!!!: Not enough memory available for Docker.\e[0m"
          echo "At least 4GB of memory required. You have $$(numfmt --to iec $$((mem_available * one_meg)))"
          echo
          warning_resources="true"
        fi
        if (( cpus_available < 2 )); then
          echo
          echo -e "\033[1;33mWARNING!!!: Not enough CPUS available for Docker.\e[0m"
          echo "At least 2 CPUs recommended. You have $${cpus_available}"
          echo
          warning_resources="true"
        fi
        if (( disk_available < one_meg * 10 )); then
          echo
          echo -e "\033[1;33mWARNING!!!: Not enough Disk space available for Docker.\e[0m"
          echo "At least 10 GBs recommended. You have $$(numfmt --to iec $$((disk_available * 1024 )))"
          echo
          warning_resources="true"
        fi
        if [[ $${warning_resources} == "true" ]]; then
          echo
          echo -e "\033[1;33mWARNING!!!: You have not enough resources to run Airflow (see above)!\e[0m"
          echo "Please follow the instructions to increase amount of resources available:"
          echo "   https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#before-you-begin"
          echo
        fi
        echo
        echo "Creating missing opt dirs if missing:"
        echo
        mkdir -v -p /opt/airflow/{logs,dags,plugins,config}
        echo
        echo "Airflow version:"
        /entrypoint airflow version
        echo
        echo "Files in shared volumes:"
        echo
        ls -la /opt/airflow/{logs,dags,plugins,config}
        echo
        echo "Running airflow config list to create default config file if missing."
        echo
        /entrypoint airflow config list >/dev/null
        echo
        echo "Files in shared volumes:"
        echo
        ls -la /opt/airflow/{logs,dags,plugins,config}
        echo
        echo "Change ownership of files in /opt/airflow to ${HA5__AIRFLOW__USER_ID}:0"
        echo
        chown -R "${HA5__AIRFLOW__USER_ID}:0" /opt/airflow/
        echo
        echo "Change ownership of files in shared volumes to ${HA5__AIRFLOW__USER_ID}:0"
        echo
        chown -v -R "${HA5__AIRFLOW__USER_ID}:0" /opt/airflow/{logs,dags,plugins,config}
        echo
        echo "Files in shared volumes:"
        echo
        ls -la /opt/airflow/{logs,dags,plugins,config}
    environment:
      <<: *airflow-common-environment
      _AIRFLOW_DB_MIGRATE: true
      _AIRFLOW_WWW_USER_CREATE: true
      _AIRFLOW_WWW_USER_USERNAME: "${HA5__AIRFLOW__USER?error}"
      _AIRFLOW_WWW_USER_PASSWORD: "${HA5__AIRFLOW__PASSWORD?error}"
      _PIP_ADDITIONAL_REQUIREMENTS: ""
    user: "0:0"

  # Serves Airflow API (including web inteface) for
  # users, workers, and others who need it.
  airflow-api:
    <<: *airflow-common
    command: "api-server"
    environment:
      <<: *airflow-common-environment
    ports:
      - "127.0.0.1:${HA5__AIRFLOW__LOCAL_PORT}:${HA5__AIRFLOW__PORT}"
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: "service_completed_successfully"
    user: "0:0"
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "--fail",
          "--insecure",
          "https://localhost:8080/api/v2/version",
        ]
      interval: "30s"
      timeout: "10s"
      retries: 5
      start_period: "30s"

  # Sheduler orchestrates workers to handle
  # the tasks that need to be run in the
  # configured sequence.
  airflow-scheduler:
    <<: *airflow-common
    command: "scheduler"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8974/health"]
      interval: "30s"
      timeout: "10s"
      retries: 5
      start_period: "30s"
    restart: "always"
    user: "0:0"
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: "service_completed_successfully"

  # Constantly parses DAG files, keeping the
  # DAG bag fresh. This service automaticaly
  # syncronizes local DAGs version with the
  # one shown in the UI, i.e. server version.
  airflow-dag-processor:
    <<: *airflow-common
    command: "dag-processor"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'airflow jobs check --job-type DagProcessorJob --hostname "$${HOSTNAME}"',
        ]
      interval: "30s"
      timeout: "10s"
      retries: 5
      start_period: "30s"
    restart: "always"
    user: "0:0"
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: "service_completed_successfully"

  # ------- HIVE METASTORE --------

  # PostgreSQL database designed to store Hive Metastore
  # meta information about schemas, tables, views, etc.
  # that exist in the Minio.
  hive-metastore-postgres:
    image: "postgres:${HA5__HIVE_METASTORE__POSTGRES__IMAGE_TAG?error}"
    command: "postgres -p ${HA5__HIVE_METASTORE__POSTGRES__PORT?error}"
    environment:
      - "POSTGRES_DB=${HA5__HIVE_METASTORE__POSTGRES__DB?error}"
      - "POSTGRES_USER=${HA5__HIVE_METASTORE__POSTGRES__USER?error}"
      - "POSTGRES_PASSWORD=${HA5__HIVE_METASTORE__POSTGRES__PASSWORD?error}"
    volumes:
      - "hive-metastore-postgres-data:/var/lib/postgresql/data"
    hostname: "${HA5__HIVE_METASTORE__POSTGRES__HOST_NAME?error}"
    networks:
      - "private"
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-p",
          "${HA5__HIVE_METASTORE__POSTGRES__PORT?error}",
          "-U",
          "${HA5__HIVE_METASTORE__POSTGRES__USER?error}",
          "-d",
          "${HA5__HIVE_METASTORE__POSTGRES__DB?error}",
        ]
      interval: "10s"
      retries: 5
      start_period: "5s"

  # Hive Metastore stores meta information about the schemas,
  # tables, views, etc. that exist in the Minio. This service
  # is used by Trino and Spark to correctly process incoming
  # SQL-queries (e.g. substitute abstract data source paths
  # with real paths).
  hive-metastore:
    build:
      context: "metastore"
      dockerfile: "Dockerfile.${MOD?error}"
      args:
        - "X__HIVE_METASTORE__IMAGE_TAG=${HA5__HIVE_METASTORE__IMAGE_TAG?error}"
    environment:
      - "METASTORE_PORT=${HA5__HIVE_METASTORE__PORT?error}"
      - "HA5__HIVE_METASTORE__POSTGRES__HOST_NAME=${HA5__HIVE_METASTORE__POSTGRES__HOST_NAME?error}"
      - "HA5__HIVE_METASTORE__POSTGRES__PORT=${HA5__HIVE_METASTORE__POSTGRES__PORT?error}"
      - "HA5__HIVE_METASTORE__POSTGRES__DB=${HA5__HIVE_METASTORE__POSTGRES__DB?error}"
      - "HA5__HIVE_METASTORE__POSTGRES__USER=${HA5__HIVE_METASTORE__POSTGRES__USER?error}"
      - "HA5__HIVE_METASTORE__POSTGRES__PASSWORD=${HA5__HIVE_METASTORE__POSTGRES__PASSWORD?error}"
      - "HA5__HIVE_METASTORE__DEFAULT_WAREHOUSE_DIR=${HA5__HIVE_METASTORE__DEFAULT_WAREHOUSE_DIR?error}"
      - "HA5__MINIO__HOST_NAME=${HA5__MINIO__HOST_NAME?error}"
      - "HA5__MINIO__API__PORT=${HA5__MINIO__API__PORT?error}"
      - "HA5__MINIO__USER=${HA5__MINIO__USER?error}"
      - "HA5__MINIO__PASSWORD=${HA5__MINIO__PASSWORD?error}"
    volumes:
      - "./logs/metastore/:/tmp/root/"
    hostname: "${HA5__HIVE_METASTORE__HOST_NAME?error}"
    networks:
      - "private"
    depends_on:
      hive-metastore-postgres:
        condition: "service_healthy"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "bash -c 'exec 3<>/dev/tcp/localhost/${HA5__HIVE_METASTORE__PORT?error}'",
        ]
      interval: 15s
      timeout: 5s
      retries: 15

  # ------- SPARK CLUSTER ---------

  # Spark master node.
  spark-master:
    build:
      context: "spark"
      dockerfile: "Dockerfile.${MOD?error}"
      args:
        - "X__SPARK__IMAGE_TAG=${HA5__SPARK__IMAGE_TAG?error}"
    hostname: "${HA5__SPARK__MASTER__HOST_NAME?error}"
    command: "/opt/spark/bin/spark-class org.apache.spark.deploy.master.Master"
    environment:
      - "SPARK_MODE=master"
      - "SPARK_MASTER_HOST=spark-master"
      - "SPARK_MASTER_PORT=${HA5__SPARK__MASTER__API__PORT?error}"
      - "SPARK_MASTER_WEBUI_PORT=${HA5__SPARK__MASTER__UI__PORT?error}"
    ports:
      - "127.0.0.1:${HA5__SPARK__MASTER__UI__LOCAL_PORT}:${HA5__SPARK__MASTER__UI__PORT?error}"
    volumes:
      - "./logs/spark:/opt/spark/logs"
    networks:
      - "private"
    depends_on:
      hive-metastore:
        condition: "service_healthy"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "bash -c 'exec 3<>/dev/tcp/spark-master/${HA5__SPARK__MASTER__API__PORT?error}'",
        ]
      interval: 15s
      timeout: 5s
      retries: 15

  # Spark worker node.
  spark-worker:
    build:
      context: "spark"
      dockerfile: "Dockerfile.${MOD?error}"
      args:
        - "X__SPARK__IMAGE_TAG=${HA5__SPARK__IMAGE_TAG?error}"
    command: "/opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://${HA5__SPARK__MASTER__HOST_NAME?error}:${HA5__SPARK__MASTER__API__PORT?error}"
    environment:
      - "SPARK_MODE=worker"
      - "SPARK_WORKER_CORES=2"
      - "SPARK_WORKER_MEMORY=2g"
      - "SPARK_WORKER_WEBUI_PORT=${HA5__SPARK__WORKER__UI__PORT}"
    ports:
      - "127.0.0.1:${HA5__SPARK__WORKER__UI__LOCAL_PORT}:${HA5__SPARK__WORKER__UI__PORT}"
    networks:
      - "private"
    depends_on:
      spark-master:
        condition: "service_healthy"

  # ------------ TRINO ------------

  # Trino coordinator and worker in one node. Configured
  # to use Minio with Iceberg.
  trino-coordinator-and-worker:
    build:
      context: "trino"
      dockerfile: "Dockerfile.${MOD?error}"
      args:
        - "X__TRINO__IMAGE_TAG=${HA5__TRINO__IMAGE_TAG?error}"
    environment:
      - "HA5__TRINO__HOST_NAME=${HA5__TRINO__HOST_NAME?error}"
      - "HA5__TRINO__PORT=${HA5__TRINO__PORT?error}"
      - "HA5__MINIO__HOST_NAME=${HA5__MINIO__HOST_NAME?error}"
      - "HA5__MINIO__API__PORT=${HA5__MINIO__API__PORT?error}"
      - "HA5__MINIO__USER=${HA5__MINIO__USER?error}"
      - "HA5__MINIO__PASSWORD=${HA5__MINIO__PASSWORD?error}"
      - "HA5__HIVE_METASTORE__PORT=${HA5__HIVE_METASTORE__PORT?error}"
      - "HA5__HIVE_METASTORE__HOST_NAME=${HA5__HIVE_METASTORE__HOST_NAME?error}"
    ports:
      - "127.0.0.1:${HA5__TRINO__LOCAL_PORT}:${HA5__TRINO__PORT?error}"
    hostname: "${HA5__TRINO__HOST_NAME?error}"
    networks:
      - "private"
    depends_on:
      hive-metastore:
        condition: "service_healthy"
      minio:
        condition: "service_healthy"

networks:
  private: {}

volumes:
  minio-data: {}
  airflow-postgres-data: {}
  hive-metastore-postgres-data: {}
